language: node_js
node_js:
  - "7.10"
  - "8.11"
  - "10.7"
before_install:
  - npm install codecov.io coveralls
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
script:
  - "npm test"
